# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1a4f87659d7d176e62e7b21e168e8ccf63633f116fded8c9b87b3e10765082bbf80eacb47670f9e3581dcaadbe8abcfd80f889e88b7126359a05f6d1228cbaa

test:
  secret_key_base: 891e69fa76d079703f7a70e9c13eb596fade1c1f34e3521920de33a23082302ac27c3226d66cec56bd454157eb0be554c27b4cfc17e65c3c6b7da92e1a5fb490

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
